apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  version: v1.27.1
  profile: default
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  values:
    pilot:
      env:
        EXTERNAL_ISTIOD: "false"
    global:
      platform: k3s
      meshID: mesh1
      multiCluster:
        clusterName: enterprise-sim
      network: network1
