apiVersion: v1
kind: Namespace
metadata:
  name: compliance-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: compliance-test
spec:
  replicas: 3
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
      - name: web
        image: ghcr.io/ktock/echo-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: compliance-test
  labels:
    app: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: web
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  namespace: compliance-test
spec:
  minAvailable: 1
  selector:
    matchLabels: { app: web }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: compliance-test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: compliance-test
type: Opaque
stringData:
  username: admin
  password: secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role
  namespace: compliance-test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: compliance-test
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: compliance-test