apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - destinationrule.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sample-app-env
    envs:
      - .env

vars:
  - name: APP_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.APP_NAME
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.NAMESPACE
  - name: REGION
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.REGION
  - name: ROUTE_HOST
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.ROUTE_HOST
  - name: K3S_INGRESS_DOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.K3S_INGRESS_DOMAIN
  - name: GATEWAY_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: sample-app-env
    fieldref:
      fieldpath: data.GATEWAY_NAME
configurations:
  - kustomizeconfig.yaml
